import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class TransferService {

  constructor() { }
  vehiclesData() {
    return [
      {
        vehicleImage: 'assets/transfer/1.webp',
        model: 'Toyota Camry',
        type: 'Economy',
        category: 'Sedan',
        price: '60',
        timeOfDeparture: '14:10',
        timeOfArrival: '17:10',
        duration: '02:00',
        class: '',
        departure: 'Jeddah Airport',
        destination: 'SWISSÔTEL AL MAQAM MAKKAH',
        dateOfDeparture: '01 nov. 2023',
        dateOfArrival: '01 nov. 2023',
        nbrpassengers: '5',
        nbrbriefcases: '3',
        childseats: true,
        stops: 'Direct',
        details: {
          model: 'Toyota Camry',
          type: 'Economy',
          price: '60',
          timeOfDeparture: '14:10',
          timeOfArrival: '17:10',
          duration: '02:00',
          departure: 'Jeddah Airport',
          destination: 'Jeddah Hotel',
          stops: {
            firststop: '',
            secondstop: '',
          },
          dateOfDeparture: '01 nov. 2023',
          dateOfArrival: '01 nov. 2023',
          nbrpassengers: '5',
          nbrbriefcases: '3',
        },
      },
      {
        vehicleImage: 'assets/transfer/2.webp',
        model: 'Hyundai Santa Fe',
        type: 'SUV',
        category: 'Sedan',
        price: '100',
        timeOfDeparture: '14:10',
        timeOfArrival: '17:10',
        duration: '02:00',
        departure: 'SWISSÔTEL AL MAQAM MAKKAH',
        class: '',
        destination: 'PULLMAN ZAMZAM MAKKAH',
        dateOfDeparture: '01 nov. 2023',
        dateOfArrival: '01 nov. 2023',
        nbrpassengers: '5',
        nbrbriefcases: '3',
        childseats: true,
        stops: 'Direct',
        details: {
          model: 'Hyundai Santa Fe',
          type: 'SUV',
          price: '100',
          timeOfDeparture: '14:10',
          timeOfArrival: '17:10',
          duration: '02:00',
          departure: 'Jeddah Airport',
          destination: 'Jeddah Hotel',
          stops: {
            firststop: '',
            secondstop: '',
          },
          dateOfDeparture: '01 nov. 2023',
          dateOfArrival: '01 nov. 2023',
          nbrpassengers: '5',
          nbrbriefcases: '3',
        },
      },
      {
        vehicleImage: 'assets/transfer/5.webp',
        model: 'Ford Transit',
        type: 'Van',
        category: 'Sedan',
        price: '180',
        timeOfDeparture: '14:10',
        timeOfArrival: '17:10',
        duration: '02:00',
        departure: 'SWISSÔTEL AL MAQAM MAKKAH',
        class: '',
        destination: 'PULLMAN ZAMZAM MAKKAH',
        dateOfDeparture: '01 nov. 2023',
        dateOfArrival: '01 nov. 2023',
        nbrpassengers: '5',
        nbrbriefcases: '3',
        childseats: true,
        stops: 'Direct',
        details: {
          model: 'Ford Transit',
          type: 'Van',
          price: '180',
          timeOfDeparture: '14:10',
          timeOfArrival: '17:10',
          duration: '02:00',
          departure: 'Jeddah Airport',
          destination: 'Jeddah Hotel',
          stops: {
            firststop: '',
            secondstop: '',
          },
          dateOfDeparture: '01 nov. 2023',
          dateOfArrival: '01 nov. 2023',
          nbrpassengers: '5',
          nbrbriefcases: '3',
        },
      },
      {
        vehicleImage: 'assets/transfer/3.webp',
        model: 'Higer KLQ6952K',
        type: 'Bus',
        category: 'Bus',
        price: '90',
        timeOfDeparture: '14:10',
        timeOfArrival: '17:10',
        duration: '02:00',
        class: 'Economy',
        departure: 'Jeddah Airport',
        destination: 'Jeddah Hotel',
        dateOfDeparture: '01 nov. 2023',
        dateOfArrival: '01 nov. 2023',
        nbrpassengers: '4',
        nbrbriefcases: '3',
        childseats: false,
        stops: '2',
        details: {
          model: 'Toyota Camry',
          type: 'Economy',
          price: '60',
          timeOfDeparture: '14:10',
          timeOfArrival: '17:10',
          duration: '02:00',
          departure: 'Jeddah Airport',
          destination: 'Jeddah Hotel',
          stops: {
            firststop: 'Jeddah',
            secondstop: 'Rabigh',
          },
          dateOfDeparture: '01 nov. 2023',
          dateOfArrival: '01 nov. 2023',
          nbrpassengers: '5',
          nbrbriefcases: '3',
        },
      },
      {
        vehicleImage: 'assets/transfer/4.webp',
        model: 'High Speed 2',
        type: 'Train',
        category: 'Train',
        price: '70',
        timeOfDeparture: '14:10',
        timeOfArrival: '17:10',
        duration: '02:00',
        class: 'Business',
        departure: 'Jeddah Airport',
        destination: 'Jeddah Hotel',
        dateOfDeparture: '01 nov. 2023',
        dateOfArrival: '01 nov. 2023',
        nbrpassengers: '4',
        nbrbriefcases: '3',
        childseats: false,
        stops: '1',
        details: {
          model: 'Toyota Camry',
          type: 'Economy',
          price: '60',
          timeOfDeparture: '14:10',
          timeOfArrival: '17:10',
          duration: '02:00',
          departure: 'Jeddah Airport',
          destination: 'Jeddah Hotel',
          stops: {
            firststop: 'Jeddah',
            secondstop: 'Rabigh',
          },
          dateOfDeparture: '01 nov. 2023',
          dateOfArrival: '01 nov. 2023',
          nbrpassengers: '5',
          nbrbriefcases: '3',
        },
      },
    ];
  }
}
